#!/usr/bin/python3.5

import requests
import os
import time

def sound(var):
    if var==1:
        dur=.5
        frequency=400
        os.system('play --no-show-progress --null --channels 1 synth %s sine %f' % (dur, frequency))
    if var==2:
        dur=.5
        frequency=600
        os.system('play --no-show-progress --null --channels 1 synth %s sine %f' % (dur, frequency))
def results():
    try:
        r=requests.get("https://httpstat.us/200",timeout=2)
        #print(r.status_code)
        if r.status_code==200:
            del r
            return 200
        else :
            del r
            return 400
    except:
        #print("400")
        return 400

def main():
    x=0
    y=0
    while True:
        m=results()
        if(m==200):
            x=0
            y=y+1
            if (y == 1):
                var=1
                sound(var)
                #print("sss")
                
        if (m==400):
            y=0
            x=x+1
            if (x==1):
                var=2
                sound(var)
                #print("yyyyy")
                
        time.sleep(2)

main()
