#!/usr/bin/python3.5

import shlex
import time
import subprocess

def sound(var):
    if var==1:
        cmd=shlex.split('play --no-show-progress --null --channels 1 synth .2 sine 400')
        subprocess.call(cmd)
    if var==2:
        cmd=shlex.split('play --no-show-progress --null --channels 1 synth .2 sine 650')
        subprocess.call(cmd)

def results():
    
    try:    
        r=list(subprocess.getstatusoutput('ping -w 1 8.8.8.8'))
        if r[0]==0:
            del r
            return 200
        
        else :
            del r
            return 400

    except:
        return 400

def main():
    x=0
    y=0
    while True:
        m=results()
        if(m==200):
            x=0
            y=y+1
            if (y == 1):
                var=1
                sound(var)
                
        if (m==400):
            y=0
            x=x+1
            if (x==1):
                var=2
                sound(var)

        time.sleep(2)

main()